package com.rout.travels.itinerary.model;
// Generated Feb 21, 2018 11:47:19 PM by Hibernate Tools 4.3.1.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ConnectionT generated by hbm2java
 */
@Entity
@Table(name = "CONNECTION_T", schema = "RT_TRAVELS")
public class ConnectionT implements java.io.Serializable {

	private long connId;
	private Long itnrRefId;
	private List<SegmentT> segmentList;

	public ConnectionT() {
	}

	public ConnectionT(long connId) {
		this.connId = connId;
	}

	public ConnectionT(long connId, Long itnrRefId) {
		this.connId = connId;
		this.itnrRefId = itnrRefId;
	}

	@Id

	@SequenceGenerator(name="connGen",sequenceName="RT_TRAVELS.CONNECTION_T_SEQ",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="connGen")
	@Column(name = "CONN_ID", unique = true, nullable = false, precision = 5, scale = 0)
	public long getConnId() {
		return this.connId;
	}

	public void setConnId(long connId) {
		this.connId = connId;
	}

	@Column(name = "ITNR_REF_ID", precision = 5, scale = 0)
	public Long getItnrRefId() {
		return this.itnrRefId;
	}

	public void setItnrRefId(Long itnrRefId) {
		this.itnrRefId = itnrRefId;
	}

}
