package com.rout.travels.itinerary.model;
// Generated Feb 21, 2018 11:47:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItineraryT generated by hbm2java
 */
@Entity
@Table(name = "ITINERARY_T", schema = "RT_TRAVELS")
public class ItineraryT implements java.io.Serializable {

	private int itnryId;

	public ItineraryT() {
	}

	public ItineraryT(int itnryId) {
		this.itnryId = itnryId;
	}

	@Id

	@Column(name = "ITNRY_ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getItnryId() {
		return this.itnryId;
	}

	public void setItnryId(int itnryId) {
		this.itnryId = itnryId;
	}

}
