package com.rout.travels.itinerary.model;
// Generated Feb 21, 2018 11:47:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SegmentT generated by hbm2java
 */
@Entity
@Table(name = "SEGMENT_T", schema = "RT_TRAVELS")
public class SegmentT implements java.io.Serializable {

	private long segId;
	private Long connRefId;
	private String carrierCode;
	private String origin;
	private String destination;
	private Date departureDate;

	public SegmentT() {
	}

	public SegmentT(long segId) {
		this.segId = segId;
	}

	public SegmentT(long segId, Long connRefId, String carrierCode, String origin, String destination,
			Date departureDate) {
		this.segId = segId;
		this.connRefId = connRefId;
		this.carrierCode = carrierCode;
		this.origin = origin;
		this.destination = destination;
		this.departureDate = departureDate;
	}

	@Id
	@SequenceGenerator(name="gen",sequenceName="SEGMENT_T_SEQ",allocationSize=1)
	
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="gen")
	

	@Column(name = "SEG_ID", unique = true, nullable = false, precision = 5, scale = 0)
	public long getSegId() {
		return this.segId;
	}

	public void setSegId(long segId) {
		this.segId = segId;
	}

	@Column(name = "CONN_REF_ID", precision = 5, scale = 0)
	public Long getConnRefId() {
		return this.connRefId;
	}

	public void setConnRefId(Long connRefId) {
		this.connRefId = connRefId;
	}

	@Column(name = "CARRIER_CODE", length = 20)
	public String getCarrierCode() {
		return this.carrierCode;
	}

	public void setCarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	@Column(name = "ORIGIN", length = 20)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "DESTINATION", length = 20)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEPARTURE_DATE", length = 7)
	public Date getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

}
